repos:
  - repo: local
    hooks:
      - id: gofmt-check
        name: gofmt -l .
        entry: bash -c 'output=$(gofmt -l .); if [ -n "$output" ]; then echo "Files not formatted:"; echo "$output"; exit 1; fi'
        language: system
        types: [go]
        pass_filenames: false

      - id: go-fmt
        name: go fmt
        entry: go fmt ./...
        language: system
        types: [go]
        pass_filenames: false

      - id: go-fix
        name: go fix
        entry: go fix ./...
        language: system
        types: [go]
        pass_filenames: false

      - id: go-vet
        name: go vet
        entry: go vet ./...
        language: system
        types: [go]
        pass_filenames: false

      - id: golangci-lint
        name: golangci-lint
        entry: golangci-lint run
        language: system
        types: [go]
        pass_filenames: false
